/** A single CMS star rating (1-5) or null when CMS suppresses the value. */
export type StarRating = number | null;

export interface StarRatings {
  overall: StarRating;
  healthInspection: StarRating;
  staffing: StarRating;
  qualityMeasures: StarRating;
}

/**
 * One hospitalization / ED metric line with the facility value alongside
 * the state and national benchmarks. Values are null when CMS data is missing.
 */
export interface MetricLine {
  /** Stable key used by the frontend (e.g. "strHospitalization"). */
  key: string;
  /** Clean, user-friendly label shown in the report. */
  label: string;
  /** Grouping: short-stay (STR) or long-stay (LT). */
  group: 'short-stay' | 'long-stay';
  /** Measure family: hospitalization or emergency department visit. */
  kind: 'hospitalization' | 'ed';
  /** How to render the value: percent (%) or rate (per 1000 days). */
  unit: 'percent' | 'rate';
  facility: number | null;
  nationalAverage: number | null;
  stateAverage: number | null;
  /** CMS measure code (e.g. "521"). */
  measureCode: string;
  /** Optional CMS footnote explaining a missing/suppressed value. */
  footnote?: string | null;
}

export interface StaffingHours {
  totalNurse: number | null;
  registeredNurse: number | null;
  lpn: number | null;
  nurseAide: number | null;
}

export interface FacilityReportData {
  ccn: string;
  /** Legal/official name from CMS ProviderInfo. */
  providerName: string;
  legalBusinessName: string | null;
  address: {
    street: string | null;
    city: string | null;
    state: string | null;
    zip: string | null;
    full: string | null;
  };
  certifiedBeds: number | null;
  averageResidentsPerDay: number | null;
  ownershipType: string | null;
  telephone: string | null;
  starRatings: StarRatings;
  staffingHours: StaffingHours;
  metrics: MetricLine[];
  careCompareUrl: string;
  /** ISO timestamp of when this snapshot was generated by our server. */
  generatedAt: string;
  /** CMS processing/refresh date from the source datasets. */
  cmsProcessingDate: string | null;
  /** CMS measure period (e.g. "20241001-20250930") for the claims metrics. */
  measurePeriod: string | null;
  /** Set when one or more upstream datasets failed but core data succeeded. */
  partial: boolean;
  warnings: string[];
}

/** Manual operational inputs entered by the Medelite user. */
export interface ManualInputs {
  facilityNameOverride?: string;
  emr?: string;
  currentCensus?: string | number;
  patientType?: string;
  previousCoverage?: string;
  previousProviderPerformance?: string;
  medicalCoverage?: string;
}

/** Full payload used to render the PDF / Word report. */
export interface ReportPayload {
  facility: FacilityReportData;
  manual: ManualInputs;
  /** Optional base64 PNG chart image embedded by the client for exports. */
  chartImage?: string;
}
